/**
 * 4.5.0-87 — RAG foundation: per-track embeddings + cosine retrieval.
 *
 * Why this exists:
 *   The pre-RAG architecture injected a pre-computed library DIGEST
 *   (top-30 artists, signature albums, per-artist breakdown, era
 *   anchors) on every AI call. That's a summary the model has to
 *   INFER from when answering specific questions. It misses:
 *     - artist details beyond the top-15 (~75% of the library)
 *     - similarity ("40 Drake AND SIMILAR" — no similarity signal
 *       in the digest at all; model uses training-data guesses)
 *     - mood/vibe queries — no semantic representation
 *     - deep-cut retrieval — digest can't compose this
 *
 *   This module fixes all four at the architecture level. Per-track
 *   embeddings + cosine similarity = the model gets the actually-
 *   relevant tracks injected per query, not a summary.
 *
 * Architecture:
 *   - One embedding per track, computed from a canonical text built
 *     from artist + title + album + genre + year + play signals.
 *   - OpenAI text-embedding-3-small, 1536 dims. $0.02/M input tokens.
 *     Full 6.8k-track library ≈ $0.50 one-time. Per-query ≈ $0.000002.
 *   - Stored as a binary file (`embeddings.bin` in userData) — Float32
 *     packed, ~42 MB for the full library. Loaded once into a Map at
 *     module init; ~10 ms cosine-similarity scan per query.
 *
 * Connection point: gated behind feature flags in the IPC handlers
 * (USE_RAG_FOR_CHAT first, expand later). Without the API key the
 * whole module is inert and the legacy digest path takes over.
 */

import { join } from 'path'
import { app } from 'electron'
import { readFile, writeFile, mkdir, stat } from 'fs/promises'
import { STATE_DIR } from '../state-dir'

// ── Config ──────────────────────────────────────────────────────────
const EMBED_MODEL = 'text-embedding-3-small'
const EMBED_DIM = 1536
const EMBED_BATCH = 100              // OpenAI accepts up to 2048 inputs per call; 100 keeps each request <2 s
const EMBED_FORMAT_MAGIC = 'EMBD'    // 4-byte header so we can detect format mismatches
const EMBED_FORMAT_VERSION = 1
const OPENAI_EMBED_URL = 'https://api.openai.com/v1/embeddings'

export function isEmbeddingsConfigured(): boolean {
  return !!process.env.OPENAI_API_KEY
}

function getEmbeddingsPath(): string {
  // 4.5.0-90 — STATE_DIR-resolved (NAS or local). Embeddings file is
  // 42 MB so SMB read adds ~200-500 ms to first-access; cached in
  // memory after that so subsequent retrievals are local-fast.
  return join(STATE_DIR, 'embeddings.bin')
}

// ── In-memory cache ─────────────────────────────────────────────────
// Map<trackId, Float32Array(EMBED_DIM)>. Loaded on first read, kept in
// memory until the file's mtime changes.
//
// 4.5.0-92 — mtime-tracked invalidation. Pre-fix the cache loaded once
// and stuck for the entire process lifetime. With embeddings.bin on
// NAS (Phase 2) AND the file potentially regenerated by either the
// desktop's `embedding-backfill` IPC OR a future mobile-side backfill,
// a stale in-memory cache silently misses new vectors. The mtime
// check on every getter is one stat call (~1 ms local SSD / ~5 ms
// SMB) — cheap enough to run every retrieval without noticeable
// latency, and guaranteed to surface external updates.
// ⚠️ TWIN: ~/JakeTunesMobile/backend/src/util/rag.ts getEmbeddingsMap — the mobile
// backend loads this SAME embeddings.bin off the NAS; both must mtime-reload so
// every device (desktop, and homemini → phone) tracks one enriched brain.
let cache: Map<number, Float32Array> | null = null
let cachedMtimeMs = 0

export async function getEmbeddingsMap(): Promise<Map<number, Float32Array>> {
  const path = getEmbeddingsPath()
  let currentMtimeMs = 0
  try {
    currentMtimeMs = (await stat(path)).mtimeMs
  } catch {
    // File missing — return whatever's in the cache (possibly empty).
    if (!cache) cache = new Map()
    return cache
  }
  if (cache && currentMtimeMs === cachedMtimeMs) return cache
  try {
    const buf = await readFile(path)
    cache = parseEmbeddingsBlob(buf)
    cachedMtimeMs = currentMtimeMs
    console.log(`[rag] reloaded embeddings cache: ${cache.size} vectors (mtime=${new Date(currentMtimeMs).toISOString()})`)
  } catch {
    if (!cache) cache = new Map()
  }
  return cache
}

export async function persistEmbeddingsMap(): Promise<void> {
  if (!cache) return
  // mkdir target = the actual STATE_DIR (NAS or local). Both are safe
  // to mkdir -p; NAS is no-op when already exists.
  await mkdir(STATE_DIR, { recursive: true })
  const blob = serializeEmbeddingsBlob(cache)
  const tmp = `${getEmbeddingsPath()}.${process.pid}.${Date.now()}.tmp`
  await writeFile(tmp, blob)
  const { rename } = await import('fs/promises')
  await rename(tmp, getEmbeddingsPath())
}

// Binary format:
//   [4-byte ASCII magic "EMBD"]
//   [2-byte version (uint16 LE)]
//   [2-byte dimension (uint16 LE)]
//   [4-byte record count (uint32 LE)]
//   [N records: 4-byte trackId (uint32 LE) + dim*4 bytes Float32 LE]
// At dim=1536 each record is 6,148 bytes. 6,800 tracks ≈ 42 MB.
function serializeEmbeddingsBlob(map: Map<number, Float32Array>): Buffer {
  const recordSize = 4 + EMBED_DIM * 4
  const buf = Buffer.alloc(12 + map.size * recordSize)
  buf.write(EMBED_FORMAT_MAGIC, 0, 4, 'ascii')
  buf.writeUInt16LE(EMBED_FORMAT_VERSION, 4)
  buf.writeUInt16LE(EMBED_DIM, 6)
  buf.writeUInt32LE(map.size, 8)
  let offset = 12
  for (const [trackId, vec] of map) {
    if (vec.length !== EMBED_DIM) continue
    buf.writeUInt32LE(trackId, offset); offset += 4
    for (let i = 0; i < EMBED_DIM; i++) {
      buf.writeFloatLE(vec[i], offset); offset += 4
    }
  }
  return buf.subarray(0, offset)
}
function parseEmbeddingsBlob(buf: Buffer): Map<number, Float32Array> {
  const out = new Map<number, Float32Array>()
  if (buf.length < 12) return out
  const magic = buf.toString('ascii', 0, 4)
  if (magic !== EMBED_FORMAT_MAGIC) return out
  const ver = buf.readUInt16LE(4)
  const dim = buf.readUInt16LE(6)
  const count = buf.readUInt32LE(8)
  if (ver !== EMBED_FORMAT_VERSION || dim !== EMBED_DIM) {
    console.warn(`[embeddings] format mismatch (file v${ver} dim${dim}, expected v${EMBED_FORMAT_VERSION} dim${EMBED_DIM}) — discarding`)
    return out
  }
  const recordSize = 4 + dim * 4
  let offset = 12
  for (let i = 0; i < count && offset + recordSize <= buf.length; i++) {
    const trackId = buf.readUInt32LE(offset); offset += 4
    const vec = new Float32Array(dim)
    for (let j = 0; j < dim; j++) {
      vec[j] = buf.readFloatLE(offset); offset += 4
    }
    out.set(trackId, vec)
  }
  return out
}

// ── Canonical embedding text per track ──────────────────────────────
// Includes play + rating signals so retrieval can weight by "tracks
// I love that fit X" rather than just "tracks that nominally fit X."
export interface EmbedTrackInput {
  artist?: string
  title?: string
  album?: string
  genre?: string
  year?: number | string
  playCount?: number
  rating?: number
  bpm?: number
}

// Grounded tempo/energy/use-case from REAL bpm + genre. The literary mood
// descriptor scored ~random on tempo queries ("fast workout" / "mellow late
// night") because bpm was never in the embed text. Adding this lifts mood
// retrieval to recall@30 0.80–0.93 (validated 2026-06-26, /tmp/validate_mood.py).
// Only CLEAR high/low get energy/use-case — bland mid-tempo filler dilutes
// precise genre queries without helping any mood search.
// ⚠️ TWIN: scripts/brain-trainer.mjs tempoEnergy() — keep these in sync.
function tempoEnergyText(t: EmbedTrackInput): string {
  const b = Number(t.bpm) || 0
  if (b <= 0) return ''
  const tempo = b >= 120 ? 'fast, up-tempo, driving' : b >= 90 ? 'mid-tempo, moderate groove' : 'slow, relaxed, downtempo'
  const g = (t.genre || '').toLowerCase()
  let mood = ''
  if (b >= 130 || /punk|metal|grunge|hardcore|techno|drum/.test(g)) mood = '. energy: high-energy and intense. good for: working out, running, parties'
  else if ((b > 0 && b <= 85) || /ambient|folk|acoustic|classical|jazz|soul/.test(g)) mood = '. energy: low-energy, mellow and calm. good for: late night, relaxing, winding down, chilling'
  return `tempo: ${b} BPM, ${tempo}${mood}`
}

export function buildEmbeddingText(t: EmbedTrackInput): string {
  const lines: string[] = []
  const artist = (t.artist || '').trim()
  const title = (t.title || '').trim()
  const album = (t.album || '').trim()
  const genre = (t.genre || '').trim()
  const year = t.year ? String(t.year).trim() : ''
  lines.push(`${artist || '?'} — ${title || '?'}`)
  if (album) lines.push(`album: ${album}${year ? ` (${year})` : ''}`)
  if (!album && year) lines.push(`year: ${year}`)
  if (genre) lines.push(`genre: ${genre}`)
  const te = tempoEnergyText(t); if (te) lines.push(te)
  const rating = Number(t.rating) || 0
  const plays = Number(t.playCount) || 0
  const sig: string[] = []
  if (rating > 0) sig.push(`★${rating}`)
  if (plays > 5) sig.push(`loved (${plays} plays)`)
  else if (plays > 0) sig.push(`${plays} plays`)
  if (sig.length) lines.push(sig.join(' '))
  return lines.join('\n')
}

// ── OpenAI batch embed ──────────────────────────────────────────────
export async function embedTexts(texts: string[]): Promise<Float32Array[]> {
  const key = process.env.OPENAI_API_KEY
  if (!key) throw new Error('OPENAI_API_KEY not set')
  const out: Float32Array[] = []
  for (let i = 0; i < texts.length; i += EMBED_BATCH) {
    const chunk = texts.slice(i, i + EMBED_BATCH)
    const res = await fetch(OPENAI_EMBED_URL, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${key}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ model: EMBED_MODEL, input: chunk }),
    })
    if (!res.ok) {
      const errText = await res.text().catch(() => '')
      throw new Error(`OpenAI embed failed: ${res.status} ${errText.slice(0, 200)}`)
    }
    const body = await res.json() as { data?: Array<{ embedding?: number[] }> }
    for (const row of body.data || []) {
      if (Array.isArray(row.embedding) && row.embedding.length === EMBED_DIM) {
        out.push(Float32Array.from(row.embedding))
      } else {
        throw new Error(`OpenAI embed returned malformed row (expected ${EMBED_DIM}-dim)`)
      }
    }
  }
  return out
}

// ── Cosine similarity + top-K retrieval ─────────────────────────────
// OpenAI embeddings are L2-normalized so cosine == dot product.
// Loop is hot-pathed: ~10 ms for 6,800 × 1536-dim on a Mac M-series.
export function cosine(a: Float32Array, b: Float32Array): number {
  let sum = 0
  const n = Math.min(a.length, b.length)
  for (let i = 0; i < n; i++) sum += a[i] * b[i]
  return sum
}
export interface RetrievedHit { trackId: number; score: number }
export function topK(query: Float32Array, all: Map<number, Float32Array>, k: number): RetrievedHit[] {
  if (all.size === 0) return []
  // Min-heap of size k would beat a sort for very large N; at 6,800
  // tracks the sort is faster (V8 sort is libc qsort-flavor, ~1ms).
  const hits: RetrievedHit[] = []
  for (const [trackId, vec] of all) {
    hits.push({ trackId, score: cosine(query, vec) })
  }
  hits.sort((a, b) => b.score - a.score)
  return hits.slice(0, k)
}

// ── Public mutation helpers (called from main/index.ts) ─────────────
export async function setEmbedding(trackId: number, vec: Float32Array): Promise<void> {
  const m = await getEmbeddingsMap()
  m.set(trackId, vec)
}
export async function embeddingsCount(): Promise<number> {
  const m = await getEmbeddingsMap()
  return m.size
}

/** Count embeddings that match live library track IDs vs orphans in the file. */
export async function analyzeEmbeddings(
  validTrackIds: Set<number>,
): Promise<{ indexed: number; stale: number; missing: number }> {
  const m = await getEmbeddingsMap()
  let indexed = 0
  let stale = 0
  for (const id of m.keys()) {
    if (validTrackIds.has(id)) indexed++
    else stale++
  }
  return { indexed, stale, missing: Math.max(0, validTrackIds.size - indexed) }
}

/** Drop embeddings whose track IDs no longer exist in library.json. */
export async function pruneStaleEmbeddings(validTrackIds: Set<number>): Promise<number> {
  const m = await getEmbeddingsMap()
  let pruned = 0
  for (const id of m.keys()) {
    if (!validTrackIds.has(id)) {
      m.delete(id)
      pruned++
    }
  }
  if (pruned > 0) await persistEmbeddingsMap()
  return pruned
}

export async function hasEmbedding(trackId: number): Promise<boolean> {
  const m = await getEmbeddingsMap()
  return m.has(trackId)
}
