/**
 * Mood index — the brain's second ear.
 *
 * A SECOND vector per track that encodes only how the song FEELS —
 * the Gemma sound/mood descriptor + grounded tempo/energy + genre —
 * with every identity signal (artist, title, album, year, ★, plays)
 * deliberately stripped. One vector per song can't serve "who is
 * this" and "what does it feel like" at once (the documented
 * single-vector tradeoff); this file is the zero-tradeoff answer.
 *
 * Validated 2026-07-07 on the full 8,351-track library before being
 * built (brain-eval worktree, mood_index_proto.py): vibe recall
 * 0.756→0.900, genre-blend 0.640→0.758 (house/dance 0.64→1.00, new
 * wave 0.60→0.95); identity queries collapse on it BY DESIGN — the
 * router (index.ts pickRetrievalIndex) sends artist/era queries to
 * embeddings.bin and vibe queries here.
 *
 * Storage: mood-index.bin in STATE_DIR — same EMBD binary format as
 * embeddings.bin (shared serialize/parse), mirrored to the NAS via
 * STATE_FILE_NAMES so the homemini backend can route its vibe
 * queries (mixes / DJ retrieve_by_vibe) the same way.
 *
 * Writers: the nightly brain-trainer (descriptor-bearing texts) and
 * the in-app auto-index (tempo+genre-only text for brand-new tracks;
 * the trainer upgrades the vector when the descriptor lands).
 */
import { join } from 'path'
import { mkdir, readFile, rename, stat, writeFile } from 'fs/promises'
import { STATE_DIR } from '../state-dir'
import {
  parseEmbeddingsBlob,
  serializeEmbeddingsBlob,
  tempoEnergyText,
  type EmbedTrackInput,
} from './embeddings'

function getMoodIndexPath(): string {
  return join(STATE_DIR, 'mood-index.bin')
}

/**
 * The mood-only embed text. Empty string when the track has nothing
 * vibe-worthy yet (no descriptor, no bpm, no genre) — callers skip
 * embedding those.
 * ⚠️ TWIN: scripts/brain-trainer.mjs moodText() — the trainer builds
 * the same text with the Gemma descriptor it owns. Keep in sync.
 * (Design source: brain-eval branch mood_index_proto.py — the
 * validated prototype these lines must keep matching.)
 */
export function buildMoodText(t: EmbedTrackInput, descriptor?: string): string {
  const lines: string[] = []
  const d = (descriptor || '').trim()
  if (d) lines.push(`sound and mood: ${d}`)
  const te = tempoEnergyText(t)
  if (te) lines.push(te)
  const genre = (t.genre || '').trim()
  if (genre) lines.push(`genre: ${genre}`)
  return lines.join('\n')
}

// mtime-tracked cache, same discipline as embeddings.ts — the file is
// regenerated by the nightly trainer while the app runs, and (phase 2)
// read off the NAS by the homemini backend.
let cache: Map<number, Float32Array> | null = null
let cachedMtimeMs = 0

export async function getMoodIndexMap(): Promise<Map<number, Float32Array>> {
  const path = getMoodIndexPath()
  let currentMtimeMs = 0
  try {
    currentMtimeMs = (await stat(path)).mtimeMs
  } catch {
    if (!cache) cache = new Map()
    return cache
  }
  if (cache && currentMtimeMs === cachedMtimeMs) return cache
  try {
    const buf = await readFile(path)
    cache = parseEmbeddingsBlob(buf)
    cachedMtimeMs = currentMtimeMs
    console.log(`[mood-index] reloaded: ${cache.size} vectors (mtime=${new Date(currentMtimeMs).toISOString()})`)
  } catch {
    if (!cache) cache = new Map()
  }
  return cache
}

export async function setMoodVector(trackId: number, vec: Float32Array): Promise<void> {
  const map = await getMoodIndexMap()
  map.set(trackId, vec)
}

export async function persistMoodIndex(): Promise<void> {
  if (!cache) return
  await mkdir(STATE_DIR, { recursive: true })
  const blob = serializeEmbeddingsBlob(cache)
  const tmp = `${getMoodIndexPath()}.${process.pid}.${Date.now()}.tmp`
  await writeFile(tmp, blob)
  await rename(tmp, getMoodIndexPath())
  cachedMtimeMs = (await stat(getMoodIndexPath())).mtimeMs
}

export async function pruneStaleMoodVectors(validTrackIds: Set<number>): Promise<number> {
  const map = await getMoodIndexMap()
  let pruned = 0
  for (const id of map.keys()) {
    if (!validTrackIds.has(id)) { map.delete(id); pruned++ }
  }
  if (pruned > 0) await persistMoodIndex()
  return pruned
}
