// 4.3.2: persistent radio show memory. Every segment generated by
// musicman-radio gets a structured entry written to disk; future
// segments can pull recent entries to drive callbacks ("like that
// thing about Steely Dan from earlier"), avoid repeating angles,
// and develop running jokes across an entire session.
//
// Storage: a single JSON file in userData. Rolling cap at 60
// entries (~one full evening of radio) so the file stays small and
// the prompt context doesn't bloat.

import { app } from 'electron'
import { join } from 'path'
import { readFile, writeFile, mkdir } from 'fs/promises'

const MEMORY_PATH = join(app.getPath('userData'), 'radio-memory.json')
const MAX_ENTRIES = 60

export interface RadioMemoryEntry {
  ts: number              // epoch ms
  transition: number      // counter value at segment time
  slot: number            // rotation slot (0-11)
  angle: string | null    // topic angle for this segment ("BACK-ANNOUNCE", "GENRE BEEF", ...)
  speakers: string[]      // ['mm', 'megan'] or includes 'giovanni' / 'stephen' / 'announcer'
  prevTrack: string       // "Title — Artist"
  nextTrack: string       // "Title — Artist"
  // Up to 3 short callback-worthy lines from this segment. We pull
  // these from the script after each generation — typically the
  // sharpest opinion, a quoted lyric, a Megan zinger, a Giovanni
  // misfire. Stored verbatim so future segments can quote them.
  callbacks: string[]
}

interface MemoryFile {
  entries: RadioMemoryEntry[]
}

let cache: MemoryFile | null = null

async function loadMemory(): Promise<MemoryFile> {
  if (cache) return cache
  try {
    const raw = await readFile(MEMORY_PATH, 'utf-8')
    const parsed = JSON.parse(raw) as MemoryFile
    cache = { entries: Array.isArray(parsed.entries) ? parsed.entries : [] }
  } catch {
    cache = { entries: [] }
  }
  return cache
}

async function saveMemory(file: MemoryFile): Promise<void> {
  try {
    await mkdir(join(app.getPath('userData')), { recursive: true })
    await writeFile(MEMORY_PATH, JSON.stringify(file, null, 2))
  } catch (err) {
    console.warn('[radio-memory] save failed:', err)
  }
}

/** Clear the persisted memory. Useful for "reset the show" — wired up
 *  to whatever UI gesture the user wants (full Radio Mode toggle off,
 *  manual reset button, etc.). */
export async function clearMemory(): Promise<void> {
  cache = { entries: [] }
  await saveMemory(cache)
}

/** Append an entry to memory and persist. Caps at MAX_ENTRIES. */
export async function appendMemory(entry: RadioMemoryEntry): Promise<void> {
  const file = await loadMemory()
  file.entries.push(entry)
  if (file.entries.length > MAX_ENTRIES) {
    file.entries = file.entries.slice(-MAX_ENTRIES)
  }
  cache = file
  await saveMemory(file)
}

/** Recent topic angles — used by the prompt to bias against immediate
 *  repetition. Returns the last N angles in newest-first order. */
export async function getRecentAngles(n = 8): Promise<string[]> {
  const file = await loadMemory()
  const out: string[] = []
  for (let i = file.entries.length - 1; i >= 0 && out.length < n; i--) {
    const a = file.entries[i].angle
    if (a) out.push(a)
  }
  return out
}

/** Recent callback-worthy lines from across the session. Newest-first.
 *  Used to drive references ("like that thing about Steely Dan earlier"). */
export async function getRecentCallbacks(n = 8): Promise<string[]> {
  const file = await loadMemory()
  const out: string[] = []
  for (let i = file.entries.length - 1; i >= 0 && out.length < n; i--) {
    for (const cb of file.entries[i].callbacks || []) {
      if (cb && out.length < n) out.push(cb)
    }
  }
  return out
}

/** Format the memory snapshot for the radio prompt. Returns a single
 *  block with recent topics + callback fuel; empty string if memory is
 *  empty (first segment of a session). */
export async function formatMemoryForPrompt(): Promise<string> {
  const angles = await getRecentAngles(8)
  const callbacks = await getRecentCallbacks(8)
  if (!angles.length && !callbacks.length) return ''
  const parts: string[] = []
  parts.push('SHOW MEMORY (continuity — refer back to these naturally if it earns it; do NOT recite them, do NOT force callbacks):')
  if (angles.length) {
    parts.push(`  • Recent topic angles (try NOT to repeat these): ${angles.slice(0, 6).join(' / ')}`)
  }
  if (callbacks.length) {
    parts.push(`  • Recent moments worth callbacks ("remember when you said…"):`)
    for (const cb of callbacks.slice(0, 6)) {
      parts.push(`    - "${cb.slice(0, 140)}"`)
    }
  }
  return parts.join('\n')
}

/** Extract callback-worthy lines from a Claude-generated script.
 *  Heuristic: take the strongest 1-3 lines based on signal markers —
 *  quotes, capitals, definitive statements, profanity. Fall back to
 *  the last MM and Megan lines (often the punchline). Output is
 *  trimmed to ~140 chars per line. */
export function extractCallbacks(script: string): string[] {
  const lines = script.split('\n').map(l => l.trim()).filter(Boolean)
  const speakerLines: { speaker: string; text: string }[] = []
  for (const raw of lines) {
    const m = raw.match(/^\[(MM|MEGAN|ANNOUNCER|GIOVANNI|STEPHEN|DJ_HANDS|DJ_STEPHEN_HANDS)\]\s*(.+)/i)
    if (m) speakerLines.push({ speaker: m[1].toUpperCase(), text: m[2].trim() })
  }
  if (speakerLines.length === 0) return []

  // Score each line — prefer strong opinions / hot takes.
  const score = (text: string): number => {
    let s = 0
    if (/[A-Z]{3,}/.test(text)) s += 2                      // capitalized punch
    if (/[!]{1,}/.test(text)) s += 1                        // exclamation
    if (/"[^"]+"/.test(text)) s += 2                        // quoted phrase
    if (/\b(fucking|shit|hell|goddamn|damn)\b/i.test(text)) s += 2  // profanity = strong opinion
    if (/\b(masterpiece|garbage|insane|trash|incredible|overrated|underrated)\b/i.test(text)) s += 2
    if (/\b(I think|I'd say|honestly|the thing is)\b/i.test(text)) s += 1
    if (text.length < 30) s -= 1                            // skip short fragments like "Yeah."
    if (text.length > 200) s -= 1                           // skip rambles
    return s
  }
  const scored = speakerLines
    .map(s => ({ ...s, score: score(s.text) }))
    .sort((a, b) => b.score - a.score)
  // Take top 2 distinct lines (different speakers if possible)
  const out: string[] = []
  const seenSpeaker = new Set<string>()
  for (const s of scored) {
    if (out.length >= 3) break
    if (s.score < 1) continue  // skip low-signal lines
    if (seenSpeaker.has(s.speaker) && out.length >= 1) continue
    out.push(s.text.replace(/\s+/g, ' ').slice(0, 140))
    seenSpeaker.add(s.speaker)
  }
  return out
}
