/**
 * Sidecar write-identity lists from @jaketunes/contracts.
 *
 * Generated by scripts/apply-jaketunes-contracts.mjs from
 * vendor/jaketunes-contracts/contracts.json — do not hand-edit the lists.
 * Bump: npm run sync:contracts
 *
 * ⚠️ TWIN: vendor/jaketunes-contracts/contracts.json (and
 * https://github.com/jrosey30/jaketunes-contracts). Tests in
 * src/main/__tests__/phone-playlist-sidecars.test.ts lock both sides.
 */

export const JAKETUNES_CONTRACTS_VERSION = "0.1.0" as const

export const desktopOwned = [
  'library.json',
  'metadata-overrides.json',
  'lyrics.json',
  'discovery-feedback.json',
  'friends.json',
  'playlists.json',
  'play-events.jsonl',
  'listening-log.jsonl',
  'live-sets.json',
  'listener-profile.json',
  'musicman-memory.json',
  'musicman-interactions.jsonl',
  'picks-cache.json',
] as const

export const mobileWritable = [
  'mobile-playlists.json',
  'playlist-additions.json',
  'mobile-stars.json',
  'mobile-plays.json',
  'mobile-metadata-overrides.json',
  'mobile-imports.json',
  'mobile-listening-log.jsonl',
  'recommendations.json',
  'recommendations-deleted.json',
] as const

export const phonePlaylistSidecarsNeverPushFromDesktop = [
  'mobile-playlists.json',
  'playlist-additions.json',
] as const

export const sidecars = {
  desktopOwned,
  mobileWritable,
  phonePlaylistSidecarsNeverPushFromDesktop,
} as const

export const notes = {
  recommendationsSingleWriter:
    "The homemini mobile backend is the SINGLE writer of recommendations.json and recommendations-deleted.json. Desktop V3 must never blunt-push those files via SYNC_FILES, STATE_FILE_NAMES, or reconcile/auto-backup. Mutations go through the backend HTTP API; when homemini is unreachable they queue in the V3-private recommendations-outbox.json and replay later.",
} as const

/** Companion aliases — same lists, matching the contracts package export style. */
export const DESKTOP_OWNED = desktopOwned
export const MOBILE_WRITABLE = mobileWritable
export const PHONE_PLAYLIST_SIDECARS_NEVER_PUSH_FROM_DESKTOP = phonePlaylistSidecarsNeverPushFromDesktop

const NEVER_BLUNT_PUSH = new Set<string>(phonePlaylistSidecarsNeverPushFromDesktop)

export function isNeverBluntPushFromDesktop(filename: string): boolean {
  return NEVER_BLUNT_PUSH.has(filename)
}

/**
 * Fail fast if a desktop push/reconcile list includes a phone-owned playlist
 * sidecar. Behavior-preserving vs current main: those names are already absent
 * from STATE_FILE_NAMES / SYNC_FILES; this makes putting them back a boot error.
 */
export function assertNoDesktopBluntPush(files: readonly string[], label: string): void {
  const hits = files.filter((f) => NEVER_BLUNT_PUSH.has(f))
  if (hits.length > 0) {
    throw new Error(
      `[jaketunes-contracts] ${label} must not blunt-push ${hits.join(', ')} (sidecars.phonePlaylistSidecarsNeverPushFromDesktop)`,
    )
  }
}

function assertContractInvariants(): void {
  for (const f of phonePlaylistSidecarsNeverPushFromDesktop) {
    if (!(mobileWritable as readonly string[]).includes(f)) {
      throw new Error(`[jaketunes-contracts] ${f} is never-push-from-desktop but not in mobileWritable`)
    }
    if ((desktopOwned as readonly string[]).includes(f)) {
      throw new Error(`[jaketunes-contracts] ${f} cannot be both desktopOwned and never-push-from-desktop`)
    }
  }
}
assertContractInvariants()
